services:
  - type: web
    name: Zomato-Zamato-App
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1,.onrender.com"
      - key: DATABASE_URL
        sync: false # Connect your Supabase Connection String here
      - key: EMAIL_HOST_USER
        value: virajdobariya61@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: jsmzaqziqbzgwpwo
      - key: RAZORPAY_KEY_ID
        value: rzp_test_RRohlnOxODtIQJ
      - key: RAZORPAY_SECRET
        value: 10VV4TyI859blM7Pf9U70YTY
      - key: CLOUDINARY_CLOUD_NAME
        value: dgjt0orlv
      - key: CLOUDINARY_API_KEY
        value: "384832215337237"
      - key: CLOUDINARY_API_SECRET
        value: DFOkprOynhkBWD-5iNtxoek4fcw

