services:
  - type: web
    name: Zomato-Zamato-App
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1,.onrender.com"
      - key: DATABASE_URL
        sync: false # Connect your Supabase Connection String here
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

