# Generated by Django 5.2.4 on 2025-08-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_restaurantowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('restaurant_name', models.CharField(max_length=255)),
                ('restaurant_address', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='owner_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RestaurantOwner',
        ),
    ]
