# Generated by Django 5.2.4 on 2025-08-13 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_restaurant_fooditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
