# Generated by Django 5.2.4 on 2025-08-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_registration_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='restaurant_name',
            field=models.CharField(default='Default Restaurant', max_length=100),
        ),
    ]
