# Generated by Django 5.2.4 on 2025-08-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_fooditem_restaurant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='restaurant_name',
            field=models.CharField(max_length=255),
        ),
    ]
