# Generated by Django 5.2.5 on 2025-10-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddResto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('seating_capacity', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='restaurant_images/')),
                ('menu', models.FileField(blank=True, null=True, upload_to='restaurant_menus/')),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
            ],
        ),
    ]
