# Generated by Django 5.2.4 on 2025-10-09 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_cart_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_resto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('members', models.PositiveIntegerField()),
                ('booking_time', models.DateTimeField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_resto', to='myapp.addresto')),
            ],
        ),
    ]
