# Generated by Django 5.2.4 on 2025-10-10 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_order_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_pay',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.registration'),
        ),
    ]
