# Generated by Django 5.2.4 on 2025-10-11 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_order_pay_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.fooditem'),
        ),
        migrations.AddField(
            model_name='order',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='order_food_images/'),
        ),
    ]
