# Generated by Django 5.2.4 on 2025-10-11 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_order_food_order_food_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='food',
        ),
        migrations.RemoveField(
            model_name='order',
            name='food_image',
        ),
    ]
