# Generated by Django 6.0 on 2026-07-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_addresto_latitude_addresto_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminowner',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
