# Generated by Django 6.0 on 2026-07-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_adminowner_is_blocked_registration_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminowner',
            name='aadhar_card_img',
            field=models.ImageField(blank=True, null=True, upload_to='aadhar_images/'),
        ),
        migrations.AddField(
            model_name='adminowner',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
