# Generated by Django 5.2.5 on 2026-07-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_deliveryboy_order_delivery_boy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='deliveryboy',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='bike_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_boys/'),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='license_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='type_of_bike',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
