# Generated by Django 5.2.5 on 2026-07-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_remove_deliveryboy_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
