# Generated by Django 5.2.5 on 2026-07-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_order_delivery_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
