# Generated by Django 5.2.5 on 2026-07-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_restaurantnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_delivery_charge', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
                ('rider_share_percentage', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('restaurant_commission_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_commission',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_earning',
            field=models.FloatField(default=0.0),
        ),
    ]
