# Generated by Django 5.2.5 on 2026-07-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_platformsettings_order_delivery_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='food_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
