# Generated by Django 5.2.5 on 2026-07-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminowner',
            name='is_accepting_orders',
            field=models.BooleanField(default=True),
        ),
    ]
