# Generated by Django 5.2.5 on 2026-07-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_superadminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='aadhar_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='aadhar_cards/'),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='bike_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
