# Generated by Django 5.2.5 on 2026-07-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_deliveryboy_aadhar_card_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
