# Generated by Django 5.2.5 on 2026-07-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_deliveryboy_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='delivery_bonus_amount',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='delivery_bonus_orders_threshold',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
