# Generated by Django 5.2.5 on 2026-07-04 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_platformsettings_delivery_bonus_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('required_orders', models.IntegerField(default=10)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryBoyTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_completed', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_claimed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to='myapp.deliveryboy')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider_progress', to='myapp.deliverytask')),
            ],
            options={
                'unique_together': {('delivery_boy', 'task')},
            },
        ),
    ]
