# Generated by Django 5.2.5 on 2026-07-04 14:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
