# Generated by Django 5.2.5 on 2026-07-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_deliverytask_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ride_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
