# Generated by Django 5.2.5 on 2026-07-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_order_ride_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_pay',
            name='wallet_used',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
