# Generated by Django 5.2.5 on 2026-07-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0057_deliveryboynotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='restaurant_commission',
            field=models.FloatField(default=0.0),
        ),
    ]
